webtalk_init -webtalk_dir C:/Users/Fabian/git/labs/Lab6_Report/Lab4_no_witchcraft.sim/sim_1/behav/xsim/xsim.dir/FSM_Test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 16 22:13:34 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d6b89b3f-8750-4792-81c9-5fd09fcfd9f2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "955def7c03a24cbeb74eb8d0756b59de" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "72" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 1700 Eight-Core Processor          " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2994 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "210 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5732_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1008526212 -regid "" -xml C:/Users/Fabian/git/labs/Lab6_Report/Lab4_no_witchcraft.sim/sim_1/behav/xsim/xsim.dir/FSM_Test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Fabian/git/labs/Lab6_Report/Lab4_no_witchcraft.sim/sim_1/behav/xsim/xsim.dir/FSM_Test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Fabian/git/labs/Lab6_Report/Lab4_no_witchcraft.sim/sim_1/behav/xsim/xsim.dir/FSM_Test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
